/**
 * The palette blocks in `src/styles/index.css`, generated from `src/lib/theme.ts`.
 *
 * The colours have to exist as static CSS — that is the whole reason a theme survives the first
 * paint without a flash, and why switching one costs two attribute writes instead of a repaint
 * driven from JavaScript. But typing eight blocks of eleven custom properties by hand is how a
 * palette ends up with one token from a different theme, so the blocks are generated from the
 * same table the swatches and the contrast tests read.
 *
 * `pnpm theme:css` prints them. `src/lib/theme.test.ts` regenerates them and fails if the
 * stylesheet has drifted, so the generator is not something anyone has to remember to run: the
 * test says so, with the text to paste.
 */
import { pathToFileURL } from "node:url";
import {
  DEFAULT_PALETTE,
  PALETTES,
  TOKEN_PROPERTIES,
  paletteById,
  type Tokens,
} from "../src/lib/theme";

export const CSS_START = "/* theme:css start — generated by scripts/theme-css.ts, do not edit by hand */";
export const CSS_END = "/* theme:css end */";

function declarations(tokens: Tokens, scheme: "light" | "dark", indent: string): string {
  const lines = [`${indent}color-scheme: ${scheme};`];
  for (const [key, property] of TOKEN_PROPERTIES) lines.push(`${indent}${property}: ${tokens[key]};`);
  return lines.join("\n");
}

function block(selector: string, tokens: Tokens, scheme: "light" | "dark"): string {
  return `${selector} {\n${declarations(tokens, scheme, "  ")}\n}`;
}

/** The generated region, start and end markers included. */
export function themeCss(): string {
  const parts: string[] = [CSS_START];

  // The default palette is also the bare `:root`, so a page with no attributes at all — the
  // prerendered HTML before the inline script, a reader with storage switched off — is the theme
  // the project shipped with.
  const fallback = paletteById(DEFAULT_PALETTE);
  parts.push(block(`:root,\n:root[data-palette="${fallback.id}"]`, fallback.light, "light"));

  for (const palette of PALETTES) {
    if (palette.id === fallback.id) continue;
    parts.push(block(`:root[data-palette="${palette.id}"]`, palette.light, "light"));
  }

  // No JavaScript, or storage that threw: no attribute is ever set, and the OS preference is
  // still worth honouring. Scoped to :not([data-theme]) so it can never outvote a real choice.
  parts.push(
    `@media (prefers-color-scheme: dark) {\n:root:not([data-theme]) {\n${declarations(fallback.dark, "dark", "  ")}\n}\n}`,
  );

  parts.push(block(`:root[data-theme="dark"]`, fallback.dark, "dark"));
  for (const palette of PALETTES) {
    parts.push(block(`:root[data-palette="${palette.id}"][data-theme="dark"]`, palette.dark, "dark"));
  }

  parts.push(CSS_END);
  return parts.join("\n\n");
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  console.log(themeCss());
}
